name: househelp
description: "HouseHelp Rwanda - Connecting you to trusted home services"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.0
  provider: ^6.1.2
  go_router: ^16.0.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  image_picker: ^1.0.8
  cached_network_image: ^3.3.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.1
  google_sign_in: ^7.1.1
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  intl_phone_number_input: ^0.7.4
  pin_code_fields: ^8.0.1
  country_code_picker: ^3.0.0
  file_picker: ^10.2.0
  form_validator: ^2.1.1
  lottie: ^3.1.2
  flutter_spinkit: ^5.2.1
  local_auth: ^2.3.0
  dio: ^5.4.3+1
  table_calendar: ^3.1.2
  flutter_xlider: ^3.5.0
  # flutterwave_standard: ^1.0.8   # REMOVE or COMMENT OUT this line
  url_launcher: ^6.2.5
  crypto: ^3.0.3
  fl_chart: ^1.0.0
  google_maps_flutter: ^2.6.0
  firebase_messaging: ^15.2.9
  firebase_core: ^3.15.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pdf: ^3.10.8
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1 
  http: ^1.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/logos/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"